[colors.bright]
black = "0x4C566A"
blue = "0x81A1C1"
cyan = "0x8FBCBB"
green = "0xA3BE8C"
magenta = "0xB48EAD"
red = "0xBF616A"
white = "0xECEFF4"
yellow = "0xEBCB8B"

[colors.normal]
black = "0x3B4252"
blue = "0x81A1C1"
cyan = "0x88C0D0"
green = "0xA3BE8C"
magenta = "0xB48EAD"
red = "0xBF616A"
white = "0xE5E9F0"
yellow = "0xEBCB8B"

[colors.primary]
background = "0x2E3440"
foreground = "0xD8DEE9"

[font]
size = 11.0

[font.bold]
family = "mononoki"
style = "Bold"

[font.bold_italic]
family = "mononoki"
style = "Bold Italic"

[font.italic]
family = "mononoki"
style = "Italic"

[font.normal]
family = "mononoki"
style = "Regular"

[window.padding]
x = 12
y = 12
