#!/usr/bin/env zsh

typeset -U PATH path
path=("$HOME/.local/share/go/bin" "$HOME/.local/bin" "$HOME/.bin" "${path[@]}")
export PATH

export EDITOR="nvim"

export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_CACHE_HOME="${HOME}/.cache"

export LESSHISTFILE=-

export HISTFILE="${XDG_CACHE_HOME}/history"
export DIRSTACKFILE="${XDG_CACHE_HOME}/dirstack"

export NPM_CONFIG_USERCONFIG="${XDG_CONFIG_HOME}/npm/npmrc"

export GOPATH="${XDG_DATA_HOME}/go"
export CARGO_HOME="${XDG_DATA_HOME}/cargo"
export RUSTUP_HOME="${XDG_DATA_HOME}/rustup"
export GNUPGHOME="${XDG_DATA_HOME}/gnupg"
export R_LIBS_USER="${XDG_DATA_HOME}/R"
# export DICTIONARY="${XDG_DATA_HOME}/hunspell.aff"

export JDK_JAVA_OPTIONS="-Dsun.java2d.opengl=true -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true"

