# Completion setup
autoload -Uz compinit 
compinit
zstyle ':completion:*' menu select
setopt COMPLETE_ALIASES

# Fuzzy matching for completions
zstyle ':completion:*' completer _complete _match _approximate
zstyle ':completion:*:match:*' original only
zstyle ':completion:*:approximate:*' max-errors 1 numeric

# Ignore completion functions for commands you don’t have
zstyle ':completion:*:functions' ignored-patterns '_*'

# cd will never select the parent directory (e.g.: cd ../<TAB>)
zstyle ':completion:*:cd:*' ignore-parents parent pwd

# History setup
HISTFILE=${HOME}/.cache/zsh_history
HISTSIZE=1000
SAVEHIST=1000

# Cmd search setup
autoload -Uz up-line-or-beginning-search down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
[[ -n "${key[Up]}"   ]] && bindkey -- "${key[Up]}"   up-line-or-beginning-search
[[ -n "${key[Down]}" ]] && bindkey -- "${key[Down]}" down-line-or-beginning-search

# Aliases
alias ls="ls --color=auto --classify=auto"
alias ll="ls -l"
alias la="ls -Al"
alias rm="rm -iv"
alias mv="mv -iv"
alias gst="git status"
alias ga="git add"
alias gaa="git add --all"
alias gc="git commit"
alias gp="git push"
alias gl="git pull"

# Window title
precmd ()  { print -Pn "\e]0;[%n@%M][%~]%#\a" } 
preexec () { print -Pn "\e]0;[%n@%M][%~]%# ($1)\a" }

# Source files
source ${HOME}/.config/broot/launcher/bash/br
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

# dircolors setup
[[ -r "${HOME}/.config/dir_colors" ]] && eval $(dircolors $HOME/.config/dir_colors)

# Prompt setup
eval "$(starship init zsh)"
