#!/bin/sh

run_cmd() {
    program=$1
    name=$(echo $program | awk '{printf $1}')
    pgrep -u "$UID" -x "$name" > /dev/null || eval "$program"
    [[ "$name" == "bash" ]] && eval "$program"
}

# Autostart
(
    run_cmd "sxhkd" &
    run_cmd "xfsettingsd" &
    run_cmd "xfce4-power-manager -no-daemon" &
    run_cmd "xfce4-screensaver --no-daemon" &
    run_cmd "nitrogen --restore" &
    run_cmd "bash -c '~/.config/polybar/launch.sh'" &
    run_cmd "picom --experimental-backends" &
    run_cmd "setxkbmap us,ru -option 'grp:win_space_toggle'" &
    run_cmd "dunst" &
    run_cmd "nm-applet" &
    run_cmd "redshift-gtk" &
    run_cmd "gxkb" &
    run_cmd "xsetroot -cursor_name left_ptr" &
    run_cmd "volumeicon" &
) 2> /tmp/autostart_bspwm_log

# Workspaces setup
bspc monitor -d 1 2 3 4 5

bspc config border_width         0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Colors
bspc config normal_border_color     "#4c566a"
bspc config focused_border_color    "#5e81ac"
bspc config presel_feedback_color   "#5e81ac"

# Rules
bspc rule -a Emacs state=tiled
bspc rule -a Skype state=floating
bspc rule -a Qalculate-gtk state=floating
bspc rule -a Steam state=floating

