#!/usr/bin/env bash

# If refreshing bspwm, remove all previous rules to prevent doubling up.
bspc rule -r "*"

daemonize() {
    program=$1
    name=$(echo "$program" | awk '{printf $1}')
    pgrep -u "$UID" -x "$name" > /dev/null || eval "${program}" >> /tmp/bspwm_log
}

daemonize "sxhkd" &
daemonize "picom" &
daemonize "dunst" &
daemonize "nm-applet" &
daemonize "redshift -l 59:30" &
daemonize "gxkb" &
daemonize "emacs --daemon" &

# Autostart
nitrogen --restore &
xsetroot -cursor_name left_ptr &
setxkbmap us,ru -option 'grp:win_space_toggle' &
bash -c '~/.config/polybar/launch.sh' &

# Workspaces setup
bspc monitor -d 1 2 3 4 5 6

bspc config border_width 2

bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true
bspc config single_monocle          true
bspc config window_gap              10

# Colors
bspc config normal_border_color     "#4c566a"
bspc config focused_border_color    "#5e81ac"
bspc config presel_feedback_color   "#5e81ac"

# Rules
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a Skype state=floating
bspc rule -a Qalculate-gtk state=floating
bspc rule -a Steam state=floating
bspc rule -a zoom state=floating

