
###############################################################
# This configuration file lets you
# - define new commands
# - change the shortcut or triggering keys of built-in verbs
# - change the colors
# - set default values for flags
#
# Configuration documentation is available at
#     https://dystroy.org/broot
###############################################################

###############################################################
# Default flags
# You can set up flags you want broot to start with by
# default, for example `default_flags="ihp"` if you usually want
# to see hidden and gitignored files and the permissions (then
# if you don't want the hidden files you can launch `br -H`)
# A popular flag is the `g` one which displays git related info.
#
default_flags = ""
icon_theme = "vscode"

###############################################################
# Verbs and shortcuts

# If $EDITOR isn't set on your computer, you should either set it using
#  something similar to
#   export EDITOR=/usr/bin/nvim
#  or just replace it with your editor of choice in the 'execution'
#  pattern.
# Example:
#  execution = "/usr/bin/nvim {file}"
#
[[verbs]]
invocation = "edit"
key = "F2"
shortcut = "e"
execution = "$EDITOR {file}"

[[verbs]]
key = "ctrl-c"
execution = ":quit"

[[verbs]]
invocation = "create {subpath}"
execution = "$EDITOR {directory}/{subpath}"

[[verbs]]
invocation = "git_diff"
shortcut = "gd"
execution = "git diff {file}"

# If $PAGER isn't set on your computer, you should either set it
#  or just replace it with your viewer of choice in the 'execution'
#  pattern.
# Example:
#  execution = "less {file}"
[[verbs]]
name = "view"
invocation = "view"
execution = "$PAGER {file}"

# If you uncomment the two next shortcuts, the left
# and right arrow keys will be used to go to the parent
# directory or to open a selected one:
#
# [[verbs]]
# key = "left"
# execution = ":parent"
#
# [[verbs]]
# key = "right"
# execution = ":focus"

# Another popular set of shorctuts for going up and down:
#
# [[verbs]]
# key = "ctrl-j"
# execution = ":line_down"
#
# [[verbs]]
# key = "ctrl-k"
# execution = ":line_up"
#
# [[verbs]]
# key = "ctrl-d"
# execution = ":page_down"
#
# [[verbs]]
# key = "ctrl-u"
# execution = ":page_up"

# If you develop using git, you might like to often switch
# to the "git status" filter:
#
# [[verbs]]
# key = "ctrl-g"
# execution = ":toggle_git_status"

###############################################################
# Skin
# If you want to change the colors of broot,
# uncomment the following bloc and start messing
# with the various values.
# Note that some of those colors might not correcly
# render on terminals with low capabilities.
#

[skin]
default = "rgb(216, 222, 233) rgb(46, 52, 64)"
tree = "rgb(216, 222, 233) none"
file = "rgb(136, 192, 208) none underlined"
directory = "rgb(129, 161, 193) none bold"
exe = "rgb(143, 188, 187) none"
link = "rgb(136, 192, 208) none"
pruning = "rgb(76, 86, 106) none Italic"
perm__ = "gray(5) None"
perm_r = "None None"
perm_w = "None None"
perm_x = "None None"
owner = "gray(12) none"
group = "gray(12) none"
sparse = "none none"                    
# TODO 
git_branch = "rgb(147, 161, 161) none"   
git_insertions = "rgb(133, 153, 0) none"  
git_deletions = "rgb(211, 1, 2) none"      
git_status_current = "none none"            
git_status_modified = "rgb(181, 137, 0) none"
git_status_new = "rgb(133, 153, 0) none"    
git_status_ignored = "rgb(88, 110, 117) none"
git_status_conflicted = "rgb(211, 1, 2) none" 
git_status_other = "rgb(211, 1, 2) none"
# ----------------------------#
selected_line = "none rgb(59, 66, 82)"
char_match = "rgb(235, 103, 139) none"
file_error = "rgb(191, 97, 106) none"
flag_label = "none none"
flag_value = "rgb(208, 135, 112) none bold"
input = "rgb(136, 192, 208) none"
status_error = "rgb(191, 97, 106) none"
status_job = "rgb(59, 66, 82) rgb(136, 192, 208)"
status_normal = "none rgb(76, 86, 106)"
status_italic = "rgb(163, 190, 140) rgb(76, 86, 106) italic"
status_bold = "rgb(136, 192, 208) rgb(76, 86, 106) bold"
status_code = "none rgb(76, 86, 106)"
status_ellipsis = "none rgb(76, 86, 106)"
scrollbar_track = "rgb(59, 66, 82) none"
scrollbar_thumb = "rgb(76, 86, 106) none"
help_paragraph = "none none"
help_bold = "rgb(129, 161, 193) none bold"
help_italic = "rgb(129, 161, 193) none italic"
help_code = "rgb(143, 188, 187) none"
help_headers = "rgb(163, 190, 140) none"
help_table_border = "none none"

# You may find other skins on
#  https://dystroy.org/broot/documentation/configuration/#colors
# for example a skin suitable for white backgrounds

